name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm' # See 'Options' for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Build the image and lambda
        run: ./mvnw install -Dnative -Dquarkus.native.container-build=true

      - name: Setup SAM
        uses: aws-actions/setup-sam@v1

      - name: Build and Deploy Lambda Function

        run: |
            # Deploy the Lambda function
            sam deploy -t ./target/sam.native.yaml -g --stack-name QuarkusLambdaTutorial --s3-bucket pm-sk-bucket
